import { ref } from 'vue'

export const keepAliveComponents = ref([
  'JsonFormatter',
  'XmlFormatter',
  'Base64Tool',
  'UrlTool',
  'UuidTool',
  'QrcodeTool',
  'Md5Tool',
  'UnicodeTool',
  'HttpStatus',
  'IdcardTool',
  'SqlInTool',
  'CronTool',
  'RegexTool',
  'DiffTool',
  'SqlParamsTool',
  'CreditCodeTool',
  'SqlFormatTool',
  'ConfigEditor',
  'LinuxManual',
  'AesTool',
  'RsaTool',
  'IdcardToolNew',
  'SqlConvertTool',
  'SqlTruncateChecker',
  'SqlParserTool',
  'WordToHtml',
])